### ISSUE TITLE
Setup on windows 11 22h2

### ISSUE THREAD

**Issue by ChrisDev1234** [shirsh94/currency_converter_pro#1]
From where do I download the software, do I need to compile it in vscode or can I just run it from the script file? I noticed that this build has multiple languages do I need to install a interpter for each one?

**Comment by shirsh94** [comment]
The currency_converter_pro is a Dart package meant to be used in Dart/Flutter projects. You can add it via pubspec.yaml, and no additional interpreters or compilation steps are needed. Let me know if you need help setting it up! 😊

**Comment by ChrisDev1234** [comment]
Where do I get flutter? Is it gui or cli? And does the tool support all currencies?
